name: Build and Release VB.NET App

on:
  push:
    branches:
      - master  # メインブランチにPushされたとき
    # または、手動でワークフローをトリガーすることも可能です
    # イベントトリガーでタグ名を指定することもできます

jobs:
  build:
    name: Build and Create Release for VB.NET Application
    runs-on: windows-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. .NET SDK をセットアップ
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      # 3. ビルド実行
      - name: Build Project
        run: |
          msbuild /p:Configuration=Release /p:Platform="Any CPU"

      # 4. ビルド済みファイルをZIP圧縮
      - name: Create ZIP Archive
        run: |
          Compress-Archive -Path .\bin\Release\* -DestinationPath vbnet_app_release.zip

      # 5. タグを自動作成（バージョン番号の決定）
      - name: Create New Tag
        run: |
          # タグ名は例えば、"v1.0" などで、コミットから取得するか自動生成する
          NEW_TAG="v$(date +'%Y.%m.%d.%H%M')"
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. GitHubリリースを作成し、ZIPファイルをアップロード
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: |
            ## リリースノート
            - 最新のビルドファイルが含まれます。
            - バージョン: ${{ steps.create_tag.outputs.new_tag }}
          files: vbnet_app_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
