name: Build Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: .NET SDKのセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: ビルドを実行
        run: |
          dotnet restore VRChat_Screenshot_Discord/VRChat_Screenshot_Discord.vbproj
          dotnet build VRChat_Screenshot_Discord/VRChat_Screenshot_Discord.vbproj --configuration Release

      - name: タグの作成
        shell: bash
        run: |
          DATE=$(date +"%Y%m%d_%H%M%S")
          VERSION="v${DATE}_001"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "$VERSION" -m "Version $VERSION"
          git push origin "$VERSION"

      - name: GitHubリリースを作成
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: リリース ${{ env.VERSION }}
          body: |
            **リリースノート**
            - バージョン: **${{ env.VERSION }}**
            - 変更点:
              - 安定性が向上しました。
              - 既知の問題を修正しました。
          draft: false
          prerelease: false

      - name: パッケージを圧縮
        shell: pwsh
        run: |
          dotnet publish VRChat_Screenshot_Discord/VRChat_Screenshot_Discord.vbproj --configuration Release --output ./output
          Compress-Archive -Path ./output/* -DestinationPath "./output/VSD-VRChatScreenshotDiscord_${{ env.VERSION }}.zip"
          echo "ZIP_NAME=VSD-VRChatScreenshotDiscord_${{ env.VERSION }}.zip" >> $GITHUB_ENV

      - name: ZIPファイルをリリースにアップロード
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./output/${{ env.ZIP_NAME }}
          tag: "${{ env.VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
