name: Build Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: .NET SDKのセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: ビルドを実行
        run: |
          dotnet restore VRChat_Screenshot_Discord/VRChat_Screenshot_Discord.vbproj
          dotnet build VRChat_Screenshot_Discord/VRChat_Screenshot_Discord.vbproj --configuration Release

    
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
